os: osx
osx_image: xcode10.2

language: bash

before_install:
        - whoami
        - echo "Start of pipeline"
        - HOMEBREW_NO_AUTO_UPDATE=1

script:
        - ls
        - chmod +x hello.sh
        - ./hello.sh
        - docker pull scratch

after_script:
        - echo "End of pipeline"
